#!/bin/sh

# Need kill/restart Pulseaudio when system resume from suspend.

. "${PM_FUNCTIONS}"

case $1 in
	thaw|resume)
		kill -9 $(pidof pulseaudio)
		systemctl restart switch-sound-device-boot.service
		systemctl stop switch-sound-device-boot.service
	;;
	*) exit $NA
		;;
esac

